spring:
  devtools:
    restart:
      additional-paths: /src/main/java
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.168.1.42:33067/wutbiolab?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: gooalgene@whutbiotest
    type: com.zaxxer.hikari.HikariDataSource
  http:
    encoding:
      charset: UTF-8
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.lewuhan.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
## 图片存放路径
gooal:
  application:
    image-path: D:\tempFile
    image-nginx-url: http://192.168.0.110:83/tempFile/
    #    export-temp-path: D:\
    #    export-nginx-url: http://192.168.0.110:83/tempFile
    export-temp-path: /tmp/data/
    export-nginx-url: http://wang-108:93/tempFile

enable:
  swagger: true